Updated versions in POM.
edgexfoundry/core-command pull request #30
Opened 2018-09-25 21:51 UTC by brandonforster

Signed-off-by: Brandon Forster <brandonforster@gmail.com>

2018-09-26 17:43 UTC, tsconn23 commented
@JPWKU What's up with the non-completed checks? Are those still valid?

2018-09-26 17:44 UTC, JPWKU commented
@tsconn23 Must have forgotten to disable those, doing it now.

2018-09-26 17:46 UTC, JPWKU requested changes

2018-09-26 17:46 UTC, JPWKU commented on pom.xml
> +	<version>0.5.0</version>
@brandonforster we still want SNAPSHOT here on the actual app version

2018-09-26 17:46 UTC, JPWKU commented on pom.xml
> +	<version>0.5.0</version>
Also we should rev the master to 0.7.0-SNAPSHOT

2019-02-05 21:07 UTC, MightyNerdEric commented
Closing PR; project is being archived.

2019-02-05 21:07 UTC, closed without merging